- name: Install packages using yum
  yum:
    name: "{{ item }}"
    state: present
  loop:
    - git
    - telnet
    - httpd

- name: Copy hosts file
  template:
     src: "../../group_templates/hosts.j2"
     dest: "/etc/hosts"
  become: true

- name: Set New Hostname as Fully Qualified Domain Name
  hostname:
     name: "{{ new_hostname }}"

- name: Disable SELinux
  selinux:
    state: disabled

- name: Stop and disable iptables
  service:
    name: iptables
    state: stopped
    enabled: no
  ignore_errors: true

- name: Disable Transparent Huge Page
  sysctl:
     name: vm.nr_hugepages
     value: 0
     state: present

- name: Disable swappiness
  sysctl:
    name: vm.swappiness
    value: 0
    state: present

- name: Disable IPv6 (temporary)
  sysctl:
     name: "net.ipv6.conf.all.disable_ipv6"
     value: "1"
     state: present
  tags: disable_ipv6_temp

- name: Disable IPv6 (permanent)
  lineinfile:
     path: /etc/sysctl.conf
     regexp: '^(\s*net.ipv6.conf.all.disable_ipv6\s*=\s*)\S+(\s*)$'
     line: 'net.ipv6.conf.all.disable_ipv6 = 1'
     backup: yes
  tags: disable_ipv6_permanent

- name: Disable Automounting
  systemd:
     name: autofs
     enabled: no
     state: stopped
  ignore_errors: true

- name: Apply sysctl settings
  command: sysctl -p
  become: true
