- name: Create folder structure and copy JDK tar
  file:
    path: "/var/www/html/{{ webserver_base_folder }}/java"
    state: directory
    owner: apache
    group: apache

#- name: Copy JDK tar file
#  copy:
#    src: "files/jdk-8u202-linux-x64.tar.gz"
#    dest: "/var/www/html/{{ webserver_base_folder }}/java/"

- name: Set ownership for files and directories
  file:
    path: "/var/www/html"
    state: directory
    owner: apache
    group: apache
