   - name: Create folder structure and copy JDK tar
     file:
       path: "/var/www/html/{{ webserver_base_folder }}/java"
       state: directory
       owner: apache
       group: apache

   - name: Debug information before the task
     debug:
       msg: "Before JDK download task"

   - name: Debug information for conditions
     debug:
       var: group_names


   - name: Download Oracle JDK tarball (only on httpd_webserver)
     get_url:
        url: "https://javadl.oracle.com/webapps/download/GetFile/{{ java_version }}-b08/1961070e4c9b4e26a04e7f5a083f551e/linux-i586/jdk-{{ java_version_number }}-linux-x64.tar.gz"
        dest: "{{ local_jdk_tar }}"
        headers:
          Cookie: "oraclelicense=accept-securebackup-cookie"
        validate_certs: no
     when: "'httpd_server' in group_names"

   - name: Copy JDK tarball to web server directory (only on httpd_server)
     ansible.builtin.copy:
        src: "{{ local_jdk_tar }}"
        dest: "{{ webserver_folder }}/{{ java_web_server_path }}"
        remote_src: yes
     when: "'httpd_server' in group_names"

   - name: Set ownership for files and directories
     file:
       path: "/var/www/html"
       state: directory
       owner: apache
       group: apache
       recurse: yes

   - name: Download JDK tarball from web server
     get_url:
        url: "http://{{ httpd_server }}:{{ httpd_port }}/{{ webserver_java_folder }}/jdk-{{ java_version }}-linux-x64.tar.gz"
        dest: "{{ local_jdk_tar }}"


   - name: Untar JDK tarball
     ansible.builtin.unarchive:
        src: "{{ local_jdk_tar }}"
        dest: "{{ java_base }}"
        remote_src: yes

   - name: Install Java with specific path
     command: "update-alternatives --install /usr/bin/java java {{ java_home }}/bin/java 1"

   - name: Configure Java
     ansible.builtin.lineinfile:
        path: /etc/profile
        line: "{{ item }}"
     with_items:
        - "export JAVA_HOME={{ java_home }}"
        - "export PATH=$PATH:$JAVA_HOME/bin"

#   - name: Set Java path for current session
#     command: "source /etc/profile"
#     become: true 

   - name: Remove JDK tar file from /tmp
     ansible.builtin.file:
        path: "{{ local_jdk_tar }}"
        state: absent


